name = "TestOrderDiscount"
type = "order_discounts"
api_version = "2022-07"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/testorderdiscount.wasm"

[ui.paths]
create = "/order-discount/new"
details = "/voluorder-discountme/:id" # Note that this isn't implemented in this tutorial

